---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: bonz-dev
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: bonz-dev
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: bonz-dev
  tags:
    karpenter.sh/discovery: bonz-dev
    Environment: dev
    Project: bonz-dev
    ManagedBy: terraform
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

